version: "3.2"

services:
  auth_service:
    image: postgres
    environment:
      POSTGRES_USER: "auth_service"
      POSTGRES_PASSWORD: "auth_service"
      POSTGRES_DB: "auth_service"
    volumes:
      - ./:/auth_service_db
    ports:
      - 5432:5432
